[project]
name = "garmin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasette>=0.65.1",
    "garmindb>=3.6.2",
]

[tool.uv.sources]
garmindb = { url = "https://storage.googleapis.com/artifacts.nelhage.com/python/garmindb-3.6.3+nelhage1-py3-none-any.whl" }
