[directory]
truncate_to_repo=false

[hostname]
ssh_only=false

[gcloud]
format=""

[kubernetes]
disabled=false

[vlang]
disabled=true

[cmake]
disabled=true

[battery]
disabled=true

[env_var.PROMPT_EXTRA]
format="($env_value )"

[nix_shell]
heuristic=true
